"""initial_schema

Revision ID: 808af8583dee
Revises: 
Create Date: 2026-04-24 01:08:25.692756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '808af8583dee'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('start_date', sa.String(length=10), nullable=False),
    sa.Column('end_date', sa.String(length=10), nullable=False),
    sa.Column('strategy_version', sa.String(length=32), nullable=True),
    sa.Column('params', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_jobs_job_id'), 'backtest_jobs', ['job_id'], unique=True)
    op.create_index(op.f('ix_backtest_jobs_status'), 'backtest_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_backtest_jobs_symbol'), 'backtest_jobs', ['symbol'], unique=False)
    op.create_table('backtest_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('total_return', sa.Float(), nullable=False),
    sa.Column('annual_return', sa.Float(), nullable=False),
    sa.Column('win_rate', sa.Float(), nullable=False),
    sa.Column('profit_factor', sa.Float(), nullable=False),
    sa.Column('sharpe_ratio', sa.Float(), nullable=False),
    sa.Column('max_drawdown', sa.Float(), nullable=False),
    sa.Column('trade_count', sa.Integer(), nullable=False),
    sa.Column('avg_holding_hours', sa.Float(), nullable=False),
    sa.Column('artifact_path', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_results_job_id'), 'backtest_results', ['job_id'], unique=True)
    op.create_table('score_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('long_score', sa.Float(), nullable=False),
    sa.Column('short_score', sa.Float(), nullable=False),
    sa.Column('neutral', sa.Float(), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('signal_strength', sa.String(length=16), nullable=False),
    sa.Column('score_trend', sa.Float(), nullable=False),
    sa.Column('score_momentum', sa.Float(), nullable=False),
    sa.Column('score_volume', sa.Float(), nullable=False),
    sa.Column('score_volatility', sa.Float(), nullable=False),
    sa.Column('score_sentiment', sa.Float(), nullable=False),
    sa.Column('score_macro', sa.Float(), nullable=False),
    sa.Column('last_price', sa.Float(), nullable=True),
    sa.Column('change_24h', sa.Float(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_score_snapshots_calculated_at'), 'score_snapshots', ['calculated_at'], unique=False)
    op.create_index(op.f('ix_score_snapshots_symbol'), 'score_snapshots', ['symbol'], unique=False)
    op.create_index('ix_score_symbol_calc_at', 'score_snapshots', ['symbol', 'calculated_at'], unique=False)
    op.create_table('symbols',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('base', sa.String(length=16), nullable=False),
    sa.Column('quote', sa.String(length=16), nullable=False),
    sa.Column('contract_type', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('qty_precision', sa.Integer(), nullable=False),
    sa.Column('min_qty', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_symbols_symbol'), 'symbols', ['symbol'], unique=True)
    op.alter_column('bot_events', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('bot_events', 'event_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('bot_events', 'level',
               existing_type=sa.TEXT(),
               type_=sa.String(length=16),
               existing_nullable=False)
    op.alter_column('bot_events', 'message',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('bot_events', 'created_at',
               existing_type=sa.TEXT(),
               server_default=None,
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.drop_index(op.f('idx_events_type'), table_name='bot_events')
    op.create_index(op.f('ix_bot_events_created_at'), 'bot_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_bot_events_event_type'), 'bot_events', ['event_type'], unique=False)
    op.alter_column('candle_cache', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('candle_cache', 'symbol',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('candle_cache', 'timeframe',
               existing_type=sa.TEXT(),
               type_=sa.String(length=8),
               existing_nullable=False)
    op.alter_column('candle_cache', 'timestamp',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('candle_cache', 'open',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               nullable=False)
    op.alter_column('candle_cache', 'high',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               nullable=False)
    op.alter_column('candle_cache', 'low',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               nullable=False)
    op.alter_column('candle_cache', 'close',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               nullable=False)
    op.alter_column('candle_cache', 'volume',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               nullable=False)
    op.drop_index(op.f('idx_candle_lookup'), table_name='candle_cache')
    op.create_index('ix_candle_symbol_tf_ts', 'candle_cache', ['symbol', 'timeframe', 'timestamp'], unique=False)
    op.create_unique_constraint('uq_candle', 'candle_cache', ['symbol', 'timeframe', 'timestamp'])
    op.alter_column('daily_pnl', 'date',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10),
               nullable=False)
    op.alter_column('daily_pnl', 'pnl_usdt',
               existing_type=sa.REAL(),
               server_default=None,
               type_=sa.Float(),
               nullable=False)
    op.alter_column('daily_pnl', 'trade_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=False)
    op.alter_column('daily_pnl', 'win_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=False)
    op.alter_column('daily_pnl', 'peak_equity',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('daily_pnl', 'min_equity',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('daily_pnl', 'updated_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.alter_column('equity_snapshots', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('equity_snapshots', 'equity',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('equity_snapshots', 'free',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('equity_snapshots', 'used',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('equity_snapshots', 'created_at',
               existing_type=sa.TEXT(),
               server_default=None,
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.drop_index(op.f('idx_equity_time'), table_name='equity_snapshots')
    op.create_index(op.f('ix_equity_snapshots_created_at'), 'equity_snapshots', ['created_at'], unique=False)
    op.alter_column('trades', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('trades', 'trade_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('trades', 'symbol',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('trades', 'direction',
               existing_type=sa.TEXT(),
               type_=sa.String(length=8),
               existing_nullable=False)
    op.alter_column('trades', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=16),
               existing_nullable=False)
    op.alter_column('trades', 'entry_price',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('trades', 'exit_price',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('trades', 'quantity',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               nullable=True)
    op.alter_column('trades', 'leverage',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('trades', 'stop_loss',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('trades', 'take_profit_1',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('trades', 'take_profit_2',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('trades', 'pnl_usdt',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('trades', 'pnl_pct',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('trades', 'entry_time',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('trades', 'exit_time',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('trades', 'exit_reason',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('trades', 'signal_confidence',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('trades', 'atr_at_entry',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('trades', 'sl_algo_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=True)
    op.alter_column('trades', 'tp_algo_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=True)
    op.alter_column('trades', 'created_at',
               existing_type=sa.TEXT(),
               server_default=None,
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.drop_index(op.f('idx_trades_direction'), table_name='trades')
    op.drop_index(op.f('idx_trades_entry_time'), table_name='trades')
    op.drop_index(op.f('idx_trades_status'), table_name='trades')
    op.create_index('ix_trades_entry_time', 'trades', ['entry_time'], unique=False)
    op.create_index(op.f('ix_trades_status'), 'trades', ['status'], unique=False)
    op.create_index(op.f('ix_trades_symbol'), 'trades', ['symbol'], unique=False)
    op.create_index('ix_trades_symbol_status', 'trades', ['symbol', 'status'], unique=False)
    op.create_index(op.f('ix_trades_trade_id'), 'trades', ['trade_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_trade_id'), table_name='trades')
    op.drop_index('ix_trades_symbol_status', table_name='trades')
    op.drop_index(op.f('ix_trades_symbol'), table_name='trades')
    op.drop_index(op.f('ix_trades_status'), table_name='trades')
    op.drop_index('ix_trades_entry_time', table_name='trades')
    op.create_index(op.f('idx_trades_status'), 'trades', ['status'], unique=False)
    op.create_index(op.f('idx_trades_entry_time'), 'trades', ['entry_time'], unique=False)
    op.create_index(op.f('idx_trades_direction'), 'trades', ['direction'], unique=False)
    op.alter_column('trades', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=sa.text("(datetime('now'))"),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('trades', 'tp_algo_id',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('trades', 'sl_algo_id',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('trades', 'atr_at_entry',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('trades', 'signal_confidence',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('trades', 'exit_reason',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('trades', 'exit_time',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('trades', 'entry_time',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('trades', 'pnl_pct',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('trades', 'pnl_usdt',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('trades', 'take_profit_2',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('trades', 'take_profit_1',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('trades', 'stop_loss',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('trades', 'leverage',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('trades', 'quantity',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=False)
    op.alter_column('trades', 'exit_price',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('trades', 'entry_price',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('trades', 'status',
               existing_type=sa.String(length=16),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('trades', 'direction',
               existing_type=sa.String(length=8),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('trades', 'symbol',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('trades', 'trade_id',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('trades', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_index(op.f('ix_equity_snapshots_created_at'), table_name='equity_snapshots')
    op.create_index(op.f('idx_equity_time'), 'equity_snapshots', ['created_at'], unique=False)
    op.alter_column('equity_snapshots', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=sa.text("(datetime('now'))"),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('equity_snapshots', 'used',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('equity_snapshots', 'free',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('equity_snapshots', 'equity',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('equity_snapshots', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('daily_pnl', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('daily_pnl', 'min_equity',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('daily_pnl', 'peak_equity',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('daily_pnl', 'win_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=True)
    op.alter_column('daily_pnl', 'trade_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=True)
    op.alter_column('daily_pnl', 'pnl_usdt',
               existing_type=sa.Float(),
               server_default=sa.text('0'),
               type_=sa.REAL(),
               nullable=True)
    op.alter_column('daily_pnl', 'date',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_constraint('uq_candle', 'candle_cache', type_='unique')
    op.drop_index('ix_candle_symbol_tf_ts', table_name='candle_cache')
    op.create_index(op.f('idx_candle_lookup'), 'candle_cache', ['symbol', 'timeframe', 'timestamp'], unique=False)
    op.alter_column('candle_cache', 'volume',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True)
    op.alter_column('candle_cache', 'close',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True)
    op.alter_column('candle_cache', 'low',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True)
    op.alter_column('candle_cache', 'high',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True)
    op.alter_column('candle_cache', 'open',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True)
    op.alter_column('candle_cache', 'timestamp',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('candle_cache', 'timeframe',
               existing_type=sa.String(length=8),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('candle_cache', 'symbol',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('candle_cache', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_index(op.f('ix_bot_events_event_type'), table_name='bot_events')
    op.drop_index(op.f('ix_bot_events_created_at'), table_name='bot_events')
    op.create_index(op.f('idx_events_type'), 'bot_events', ['event_type', 'created_at'], unique=False)
    op.alter_column('bot_events', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=sa.text("(datetime('now'))"),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('bot_events', 'message',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('bot_events', 'level',
               existing_type=sa.String(length=16),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('bot_events', 'event_type',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('bot_events', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_index(op.f('ix_symbols_symbol'), table_name='symbols')
    op.drop_table('symbols')
    op.drop_index('ix_score_symbol_calc_at', table_name='score_snapshots')
    op.drop_index(op.f('ix_score_snapshots_symbol'), table_name='score_snapshots')
    op.drop_index(op.f('ix_score_snapshots_calculated_at'), table_name='score_snapshots')
    op.drop_table('score_snapshots')
    op.drop_index(op.f('ix_backtest_results_job_id'), table_name='backtest_results')
    op.drop_table('backtest_results')
    op.drop_index(op.f('ix_backtest_jobs_symbol'), table_name='backtest_jobs')
    op.drop_index(op.f('ix_backtest_jobs_status'), table_name='backtest_jobs')
    op.drop_index(op.f('ix_backtest_jobs_job_id'), table_name='backtest_jobs')
    op.drop_table('backtest_jobs')
    # ### end Alembic commands ###
